//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContaConmigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorId { get; set; }
        public string Name_Don { get; set; }
        public string Last_Name_Don { get; set; }
        public int CityId { get; set; }
        public Nullable<System.DateTime> Last_Date_Blood_Extract { get; set; }
        public int BloodGroupId { get; set; }
        public int BloodFactorId { get; set; }
    
        public virtual BloodFactor BloodFactor { get; set; }
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual City City { get; set; }
    }
}
