//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContaConmigo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RequestDonor
    {
        public int RequestDonorId { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string Name_Request_Don { get; set; }
        [Required]
        [Display(Name = "Apellido")]
        public string Last_Name_Request_Don { get; set; }
        [Required]
        [Display(Name = "Teléfono")]
        public string Phone_Number { get; set; }
        [Required]
        [Display(Name = "Ciudad")]
        public int CityId { get; set; }
        [Required]
        [Display(Name = "Código Postal")]
        public int ZipCode { get; set; }
        [Required]
        [Display(Name = "Institución")]
        public int InstitutionId { get; set; }
        [Required]
        [Display(Name = "Fecha Límite Recepción")]
        public System.DateTime Last_Date_Replacement { get; set; }
        [Required]
        [Display(Name = "Cant. Donantes Requeridos")]
        public int AmountDonor { get; set; }
        [Required]
        [Display(Name = "Grupo Sanguíneo")]
        public int BloodGroupId { get; set; }
        [Required]
        [Display(Name = "Factor Sanguíneo")]
        public int BloodFactorId { get; set; }
        [Display(Name = "Comentarios")]
        public string Comments { get; set; }
                        
        public virtual BloodFactor BloodFactor { get; set; }
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual City City { get; set; }
        public virtual Institution Institution { get; set; }
    }
}
