//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContaConmigo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorRequestDonor
    {
        public int DonorRequestDonor1 { get; set; }
        public int RequestDonorId { get; set; }
        public int DonorId { get; set; }
    
        public virtual Donor Donor { get; set; }
        public virtual RequestDonor RequestDonor { get; set; }
    }
}
