//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContaConmigo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContaConmigoEntities : DbContext
    {
        public ContaConmigoEntities()
            : base("name=ContaConmigoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<GroupFactorBlood> GroupFactorBloods { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<RequestDonor> RequestDonors { get; set; }
        public virtual DbSet<RequestDonorBlood> RequestDonorBloods { get; set; }
        public virtual DbSet<UserContaConmigo> UserContaConmigoes { get; set; }
    }
}
