//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContaConmigo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDonor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestDonor()
        {
            this.DonorRequestDonors = new HashSet<DonorRequestDonor>();
            this.RequestDonorBloods = new HashSet<CheckBoxListItem>();
        }
    
        public int RequestDonorId { get; set; }
        public string Name_Request_Don { get; set; }
        public string Last_Name_Request_Don { get; set; }
        public int CityId { get; set; }
        public System.DateTime Last_Date_Replacement { get; set; }
        public int AmountDonor { get; set; }
        public int InstitutionId { get; set; }
        public string Comment { get; set; }
        public string Phone_Number { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Completed { get; set; }
        public byte[] Photo { get; set; }
        public int UserId { get; set; }
        public int GroupFactorBloodId { get; set; }
        public string ProvinceDescription { get; set; }

        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonorRequestDonor> DonorRequestDonors { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckBoxListItem> RequestDonorBloods { get; set; }
    }
}
